version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "resume-visitor-counter"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-773gag2puoix"
s3_prefix = "resume-visitor-counter"
region = "ap-southeast-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
